### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by antranapp** [SwiftFiddle/swiftfiddle-formatter#8] opened 2021-08-12 03:38 UTC
There seems to be a SSL issue

<img width="734" alt="Screenshot 2021-08-12 at 11 38 22 AM" src="https://user-images.githubusercontent.com/478757/129134850-b1df8ad6-9725-469a-af52-117eb6e02cc4.png">

**Comment by kishikawakatsumi** [comment] 2021-08-12 04:25
@antranapp I can't reproduce it in my environment, can you tell me more about how it happens?

**Comment by kishikawakatsumi** [comment] 2021-08-14 18:56
Close this issue for now because I cannot reproduce it. Feel free to reopen if you still have the same error or you have further information.

**Closed by kishikawakatsumi** 2021-08-14 18:56 UTC

**Comment by antranapp** [comment] 2021-08-14 21:53
Sorry for being late. I think my corporate firewall caused the problem. Opening it in home network seems to be fine.

**Comment by kishikawakatsumi** [comment] 2021-08-14 21:54
Thank you for your reply. Happy to here that 😄
